services:
  app:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodburi
      - JWT_SECRET='SUPERSECRET'
      - ALLOWED_ORIGINS=http://localhost:4000,https://example.com
