name: Build, Push and Deploy to DigitalOcean

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action/deploy@v2
        env:
          IMAGE_DIGEST: ${{ steps.build.outputs.digest }}
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          app_spec_location: .do/app.yaml
